_target_: TS2VEC
dropout: 0.0
device: 2
n_layers: 1


name: TS2VEC

params:
  dropout: 0.0
  device: 2
  n_layers: 1

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1
  n_layers:
    optuna_type: int
    low: 1
    high: 3
    step: 1

attack_train_mode: False